---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    targetPort: metrics
    protocol: TCP
  selector:
    name: node-exporter