---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: kube-state-metrics
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  selector:
    name: kube-state-metrics