---
apiVersion: v1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus
spec:
  replicas: 1
  template:
    metadata:
      name: prometheus
      labels:
        name: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.34.0
        # image: quay.io/prometheus/prometheus:v2.0.0-beta.5
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume-prometheus
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume-prometheus
        configMap:
          name: prometheus